In [ ]:
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
train_images.shape 

(60000, 28, 28)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
X_train=train_images.reshape(60000,28*28)
X_test=test_images.reshape(10000,28*28)

In [ ]:
X_train.shape

(60000, 784)

In [ ]:
from tensorflow.keras.utils import to_categorical
y_train=to_categorical(train_labels)
y_test=to_categorical(test_labels)

In [ ]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [ ]:
from keras import models 
from keras import layers

In [ ]:
NN=models.Sequential()


In [ ]:
NN.add(layers.Dense(512,activation='relu',input_shape=(28*28,)))
NN.add(layers.Dense(10,activation='softmax')) 

In [ ]:
network.summary()

NameError: ignored