In [ ]:
import numpy as np 

In [ ]:
from numpy import mean
from numpy import cov 
from numpy.linalg import eig 

In [ ]:
from sklearn.decomposition import PCA 

In [ ]:
A = np.array ([[1,3], [1,2], [2,3], [0,3],[5,4],[4,5],[5,5],[3,4]])
print(A)

[[1 3]
 [1 2]
 [2 3]
 [0 3]
 [5 4]
 [4 5]
 [5 5]
 [3 4]]


In [ ]:
pca = PCA()

In [ ]:
pca.fit(A)

PCA()

In [ ]:
print(pca.components_.T)

[[ 0.89554989  0.44496113]
 [ 0.44496113 -0.89554989]]


In [ ]:
print(pca.explained_variance_)

[4.53931268 0.28211589]


In [ ]:
B = pca.transform(A)
B

array([[-1.73336927, -0.16334315],
       [-2.17833039,  0.73220673],
       [-0.83781938,  0.28161797],
       [-2.62891915, -0.60830428],
       [ 2.2937914 ,  0.72095147],
       [ 1.84320264, -0.61955954],
       [ 2.73875252, -0.17459842],
       [ 0.50269163, -0.16897078]])

In [ ]:
print(pca.explained_variance_ratio_)

[0.94148707 0.05851293]
