In [23]:
import numpy as np 

In [24]:
np.random.seed(1)
X=np.random.randn(2,3)
Y= (np.random.randn(1,3)>0)
print(X,Y)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]] [[ True False  True]]


In [25]:
## sigmoid 
def sig(Z):
    s=1/(1+np.exp(-Z))
    return s 

In [26]:
sig(1)

0.7310585786300049

In [27]:
## tanh function
def tan(Z):
    s=(np.exp(Z)-np.exp(-Z))/((np.exp(Z)+np.exp(-Z)))
    return s

In [28]:
np.tanh(1)

0.7615941559557649

In [29]:
tan(1)

0.7615941559557649

In [30]:
## relu function 
def relu(Z):
    s=np.maximum(0,Z)
    return s 

In [31]:
k = np.array([2,-3,5])
relu(k) 

array([2, 0, 5])

In [32]:
## leacky relu 
def lrelu(Z):
    s=np.maximum(0.01,Z)
    return s

In [33]:
lrelu(k)

array([2.  , 0.01, 5.  ])

In [34]:
def shape(X,Y):
    n_x=X.shape[0]
    n_h=4
    n_y=Y.shape[0]
    
    return(n_x,n_h,n_y)

In [35]:
n_x,n_h,n_y=shape(X,Y)

In [36]:
def int_parameters(n_x,n_h,n_y):
    np.random.seed(2)
    W1=np.random.randn(n_h,n_x)*0.01
    b1=np.random.randn(n_h,1)
    W2=np.random.randn(1,n_h)*0.01
    b2=np.random.randn(n_y,1)
    
    parameters ={"W1":W1,"b1":b1,"W2":W2,"b2":b2}
    
    return parameters 

In [37]:
parameters=int_parameters(n_x,n_h,n_y)

In [38]:
parameters["W1"]

array([[-0.00416758, -0.00056267],
       [-0.02136196,  0.01640271],
       [-0.01793436, -0.00841747],
       [ 0.00502881, -0.01245288]])

In [39]:
def ForwardPropagation(X,parameters):
    W1=parameters["W1"]
    b1=parameters["b1"]
    W2=parameters["W2"]
    b2=parameters["b2"]
    
    Z1=np.dot(W1,X)+b1
    A1=tan(Z1)
    Z2=np.dot(W2,A1)+b2
    A2=sig(Z2)
    
    catch={"Z1":Z2,"A1":A1,"Z2":Z2,"A2":A2}
    
    return A2,catch
    

In [40]:
A2,catch=ForwardPropagation(X,parameters)

In [41]:
def compute_cost(A2,Y):
    m=Y.shape[1]
    logp=np.multiply(Y,np.log(A2))+np.multiply((1-Y),np.log(1-A2))
    cost=-np.sum(logp)/m
    return cost

In [42]:
compute_cost(A2,Y)

0.6955024061016157

In [58]:
def BackwardPropagation(parameters,catch,X,Y):
    W1=parameters["W1"]
    b1=parameters["b1"]
    W2=parameters["W2"]
    b2=parameters["b2"]
    A1=catch["A1"]
    A2=catch["A2"]
    
    m= Y.shape[1]
    
    dZ2=A2-Y
    dW2=np.dot(dZ2,A1.T)/m
    db2=np.sum(dZ2,axis=1,keepdims=True)/m
    dZ1=np.dot(W2.T,dZ2)*(1-A2**2)
    dW1=np.dot(dZ1,X.T)/m
    db1=np.sum(dZ1,axis=1,keepdims=True)/m
    
    grade={"dW1":dW1,"db1":db1,"dW1":dW1,"db2":db2}
    
    return grade
    

In [60]:
grade

NameError: name 'grade' is not defined

In [44]:
BackwardPropagation(parameters,catch,X,Y)

{'dW1': array([[-8.92869471e-05,  2.22134454e-04],
        [ 2.40292751e-03, -5.97817495e-03],
        [-1.15868019e-03,  2.88264746e-03],
        [ 1.28141689e-03, -3.18800059e-03]]),
 'db1': array([[-5.32950994e-05],
        [ 1.43429991e-03],
        [-6.91612580e-04],
        [ 7.64873730e-04]]),
 'db2': array([[-0.17027588]])}

In [56]:
def update(parameters,grade,lr=0.01):
    W1=parameters["W1"]
    b1=parameters["b1"]
    W2=parameters["W2"]
    b2=parameters["b2"]
    
    dW1=grade["dW1"]
    db1=grade["db1"]
    dW2=grade["dW2"]
    db2=grade["db2"]
    
    W1=W1-lr*dW1
    b1=b1-lr*db1
    W2=W2-lr*dW2
    b2=b2-lr*db2
    
    parameters={"W1":W1,"db1":db2,"dW2":dW2,"db2":db2}
    return parameters
    

In [57]:
update(parameters,grade,lr=0.01)

NameError: name 'grade' is not defined