In [1]:
import numpy as np 

In [10]:
A = np.array(([1,2,3,5],[4,5,8,9],[12,5,7,11]))

In [11]:
A.shape

(3, 4)

In [12]:
u,o,vt= np.linalg.svd(A)

In [13]:
u

array([[-0.2495473 , -0.41518484,  0.87484152],
       [-0.56943299, -0.66780371, -0.47935819],
       [-0.78324467,  0.61778617,  0.06977134]])

In [14]:
o

array([23.15131969,  5.16520824,  1.15629594])

In [15]:
vt

array([[-0.51514192, -0.31369628, -0.46592672, -0.64740693],
       [ 0.83772698, -0.20917984, -0.43821681, -0.24984661],
       [-0.17758014, -0.25793674, -0.62435709,  0.71562012],
       [ 0.03616075, -0.88955443,  0.44839329,  0.07955365]])